---
deployment:
  tasks:
    - export APIPATH=/home/$(whoami)/face-app/api

    # Deploy Backend API
    - /bin/cp -R api/src $APIPATH
    - /bin/cp api/package.json $APIPATH
    - /bin/cp api/package-lock.json $APIPATH
