---
deployment:
  tasks:
    # Define destination paths (cPanel typically uses /home/username/...)
    - export DEPLOYPATH=/home/$(whoami)/face-app/client
    - export APIPATH=/home/$(whoami)/face-app/api
    
    # 1. Deploy Frontend
    # Copies the contents of the client folder to client directory on the server
    - /bin/cp -R client/* $DEPLOYPATH
    
    # 2. Deploy Backend API
    - /bin/cp -R api/* $APIPATH
