FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    build-essential \
    python3-dev \
    libglib2.0-0 \
    libgl1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 user
USER user

ENV HOME=/home/user \
    INSIGHTFACE_HOME=/home/user/.insightface \
    PATH=/home/user/.local/bin:$PATH

WORKDIR /workspace

RUN pip install --no-cache-dir --upgrade pip

COPY --chown=user ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

EXPOSE 7860

CMD ["python", "app.py"]
