name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push to Hugging Face Hub
        uses: huggingface/hub-actions@main
        with:
          repo-token: ${{ secrets.HF_TOKEN }}
          repo-id: ${{ secrets.REPO_ID }}
