name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # important for big files (models, datasets)

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          REPO_ID: ${{ secrets.REPO_ID }} # format: username/space-name
        run: |
          git remote add space https://huggingface.co/spaces/$REPO_ID
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$REPO_ID main --force
