name: Sync to HF Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to hub
        uses: huggingface/hub-actions@main
        with:
          repo-token: ${{ secrets.HF_TOKEN }}
          repo_id: ${{ secrets.REPO_ID }}
